breithbarbot_cropper:
    mappings:
        # An example of a custom mapping name
        user_avatar:
            routes:
                # A custom route which will take care of saving the image
                path_add: 'app_cropper_avatar_add'

                # Your custom route that will delete the image + Show the delete button in the modal. (Optional parameter)
                path_delete: 'app_cropper_avatar_delete'

            # Definition of cropped image properties (width, height and ratio)
            width:  400
            height: 400
            ratio:  1

        # Another example...
        note_image:
            routes:
                path_add: 'app_cropper_note_add'
            width:  400
            height: 225
            ratio:  '16/9'
